import type { DemoAccount, RequestDefinition } from '../../types/api';

const JADWA_CUSTODY_LOGIN =
  'q4QVUyxEBe7sm99Gz7YNSM8KDabm2YiZuAO2urfKYot2H7QMvm6bPXxyHiIKAaahRQlF6/FVorOQL5iOWYH15RKtYrdoyC9fE3FEIi8V5N4fG9gh619GCyxsyw7jhCzoD7hYwe9cF/KmQ4c6ShpLc/BRznyowa2/s29q0DlRfS0B/M167wzI49151xuMPXi9zNQ7WKbnaehyrQ6tit0YadcqwB59qHweSIgvD7v50A3KKDsK9YlgHxfPFvWhSTmh7Q4RFSuJWdytWqbo3D64ZfPQAGZNjbq/xL7z4qoqgtU9ChniHxRArHxqZsEJFHxHi9iY9E3u5j5iuV3/RfXvmPZxaGecT58HXV1hBDWbF8U=';
const TRADING_100_LOGIN =
  'GiR6A35Vj1rwfNHaYkjoieLMcn23ePCHPvpaWF0LwjnNi3OOXKhCaOxuxPgr5NJuOe6DPvaH8RFCvzLQnuKtiRx/YJuUO6bx36FFdeT5fx1bdXLUVYpodx9R3t5dM12mRDMm+PqnzDH0QDTP0X/Nry8xYSd2DRG6qbJhaUOWF3umyOjaT3MB+EdjSLShGq2qjOzjKp4ozjfzUyaWyt6fNLc3LUMWAFn36qzpADuqSYvMYWzbwzHR+5DZjj7C9vqJ3f4kc6/1wszHzZCoghRj7ZVYsapWns6A2jreW10+TtIwYADFU4S3EKhTW5buWKr49aJ4Ctq4umc5eBVC3LE9OPZxaGecT58HXV1hBDWbF8U=';
const TDWL_ICM_LOGIN =
  'GzBti3v9XXv5DivP1qjhPta0AdFG9goX4Mafsx5hJJBa/39ib3LNLOmEKrOJzNLJlDTDU0pTJE+hopz5ZNE338YkCMXZzAUI8eZtfkED/zHBRni4QxFS+1Fo+msEylF3gbMJJ50z3hDgXBA4Rh1yKLl8DXGkaasIuB2NU4PwL0fgaSVz+XfwiyCmOboL04BnWJAOyC3EEKHgjkmf06FbEHiiEQxVsSil++z9RS2odxTC7Z4XZb362VdyEja+Y/gn0JkCkOAAg7Vh0X2gljI9yQ93rXOvUfjBCzHvjYx5WUWaiKxDfpeG71levYiLLUjPJQ+91mwdPOFN71XE7jvgrvZxaGecT58HXV1hBDWbF8U=';

// Only requests present in the provided "DFN LWAPI GW APIs - Rest" collection snippet are implemented.
export const demoAccounts: DemoAccount[] = [
  {
    id: 'jadwa-custody-1000016',
    customerReference: '1000016',
    tradingAccount: '001000016011',
    accountType: 'Jadwa Custody',
    symbolHints: '1140 / 2222 / 7010',
    lgnNme: JADWA_CUSTODY_LOGIN,
  },
  {
    id: 'trading-account-1009665',
    customerReference: '1009665',
    tradingAccount: '100 trading account',
    accountType: 'Trading Account',
    symbolHints: 'No symbol hints in collection comment',
    lgnNme: TRADING_100_LOGIN,
  },
  {
    id: 'tdwl-icm-1008051',
    customerReference: '1008051',
    tradingAccount: '001008051001',
    accountType: 'TDWL - ICM',
    symbolHints: 'ICM / Saudi exchange',
    lgnNme: TDWL_ICM_LOGIN,
  },
];

export const requestDefinitions: RequestDefinition[] = [
  {
    id: 'auth-login-classic',
    name: 'Trade Authentication – Classic',
    category: 'Authentication & Authorization',
    method: 'POST',
    endpoint: '/Auth/Login',
    requiresAuth: false,
    description: 'First request. Uses encrypted lgnNme and stores tokens when authSts is 1 or 9.',
    body: { msgType: 1, lgnNme: TDWL_ICM_LOGIN },
  },
  {
    id: 'auth-refresh',
    name: 'Refresh Token - Classic',
    category: 'Authentication & Authorization',
    method: 'POST',
    endpoint: '/Auth/Refresh',
    requiresAuth: true,
    description: 'Sends current tradeToken header and refreshToken body; replaces tokens on authSts 1.',
    body: { msgType: 3, refreshToken: '<current refreshToken>' },
  },
  {
    id: 'auth-logout',
    name: 'Logout Service',
    category: 'Authentication & Authorization',
    method: 'POST',
    endpoint: '/Auth/Logout',
    requiresAuth: true,
    description: 'Clears local session after status 1.',
    body: { msgType: 402, customerId: '<current customerId>' },
  },
  {
    id: 'auth-verify',
    name: 'Token Verification',
    category: 'Authentication & Authorization',
    method: 'POST',
    endpoint: '/Auth/Verify',
    requiresAuth: true,
    description: 'Verifies the current tradeToken using msgType 468.',
    body: { msgType: 468 },
  },
  {
    id: 'auth-otp',
    name: 'OTP Service',
    category: 'Authentication & Authorization',
    method: 'POST',
    endpoint: '/Auth/OTP',
    requiresAuth: true,
    description: 'Verifies OTP using selected login name and current tradeToken header.',
    body: { msgType: 406, lgnNme: '<selected login name>', otp: '<entered OTP>' },
  },

  {
    id: 'customer-profile',
    name: 'Customer Profile',
    category: 'Customer',
    method: 'POST',
    endpoint: '/Customer/Profile',
    requiresAuth: true,
    description: 'Loads the authenticated customer profile using the current tradeToken header.',
    body: { msgType: 0 },
  },
  {
    id: 'customer-details',
    name: 'Customer Details',
    category: 'Customer',
    method: 'POST',
    endpoint: '/Customer/Details',
    requiresAuth: true,
    description: 'Loads customer trading/cash accounts and stores default tradingAccId and cashAccId like Postman tests.',
    body: { msgType: 6, customerId: '<current customerId>' },
  },
  {
    id: 'customer-buying-power',
    name: 'Buying Power',
    category: 'Customer',
    method: 'POST',
    endpoint: '/Customer/BuyingPower',
    requiresAuth: true,
    description: 'Requests buying power for the default cash account from Customer Details.',
    body: { msgType: 46, cashAccId: '<default cashAccId>' },
  },
  {
    id: 'customer-symbol-marginability-buying-power',
    name: 'Symbol Marginability Buying Power',
    category: 'Customer',
    method: 'POST',
    endpoint: '/Customer/BuyingPower',
    requiresAuth: true,
    description: 'Requests symbol marginability buying power using default cash/trading accounts for TDWL symbol 1050.',
    body: { msgType: 46, cashAccId: '<default cashAccId>', tradingAccId: '<default tradingAccId>', symbol: '1050', exchange: 'TDWL' },
  },

  {
    id: 'order-list',
    name: 'Order List',
    category: 'Order',
    method: 'POST',
    endpoint: '/Order/List',
    requiresAuth: true,
    description: 'Lists orders for the default trading account saved from Customer Details.',
    body: { msgType: 23, tradingAccId: '<default tradingAccId>' },
  },
  {
    id: 'order-execution-history',
    name: 'Order Execution History',
    category: 'Order',
    method: 'POST',
    endpoint: '/Order/Executions',
    requiresAuth: true,
    description: 'Loads execution history for the collection sample clOrdId and remoteClOrdID.',
    body: { msgType: 48, clOrdId: '250516000000011', remoteClOrdID: '250516000000011' },
  },
  {
    id: 'holdings-list',
    name: 'Holdings List',
    category: 'Order',
    method: 'POST',
    endpoint: '/Customer/Holdings',
    requiresAuth: true,
    description: 'Loads holdings for the default trading account using the collection Customer/Holdings request.',
    body: { msgType: 23, tradingAccId: '<default tradingAccId>' },
  },
  {
    id: 'order-new',
    name: 'New Order',
    category: 'Order',
    method: 'POST',
    endpoint: '/Order/New',
    requiresAuth: true,
    description: 'Creates an order using the Postman sample payload. Review carefully before sending.',
    body: { msgType: 2, symbol: '1010', exg: 'TDWL', ordTyp: '2', ordSide: '1', price: 1.6, ordQty: 1500, tif: 0, disQty: 0, minQty: 100, tradeDate: '<yyyyMMdd>', dayOrd: 0, tradingAccId: '<default tradingAccId>', remoteClOrdID: '<random UUID>', marketCode: 'ALL', instruTyp: 0 },
  },
  {
    id: 'order-amend',
    name: 'Amend Order',
    category: 'Order',
    method: 'POST',
    endpoint: '/Order/Update',
    requiresAuth: true,
    description: 'Amends the collection sample order. Review clOrdId and tradingAccId before sending.',
    body: { msgType: 15, clOrdId: '250323000000041', tradingAccId: '<default tradingAccId>', symbol: '1010', exg: 'TDWL', ordTyp: '2', ordSide: '1', price: 2.6, ordQty: 1800, tif: 0, disQty: 0, minQty: 100, tradeDate: '<yyyyMMdd>', dayOrd: 0 },
  },
  {
    id: 'order-cancel',
    name: 'Cancel Order',
    category: 'Order',
    method: 'POST',
    endpoint: '/Order/Cancel',
    requiresAuth: true,
    description: 'Cancels the collection sample order. Review clOrdId before sending.',
    body: { msgType: 16, clOrdId: '250323000000071', tradingAccId: '<default tradingAccId>', symbol: '1010', exg: 'TDWL', ordTyp: '2', ordSide: '1', tif: 0 },
  },
  {
    id: 'order-commission',
    name: 'Commission Service',
    category: 'Order',
    method: 'POST',
    endpoint: '/Order/Commission',
    requiresAuth: true,
    description: 'Calculates commission for the collection sample order details.',
    body: { msgType: 47, tradingAccId: '<default tradingAccId>', symbol: '1010', exg: 'TDWL', ordQty: 1500, price: 1.6, ordTyp: '2', side: '1' },
  },
  {
    id: 'order-search',
    name: 'Order Search',
    category: 'Order',
    method: 'POST',
    endpoint: '/Order/Search',
    requiresAuth: true,
    description: 'Searches orders using the collection sample filters and today as endDte.',
    body: { msgType: 24, tradingAccId: ['<default tradingAccId>'], strDte: '20250301', endDte: '<yyyyMMdd>', symbol: '1010', exg: 'TDWL', ordQty: 1500, price: 1.6, ordTyp: '2', side: '1' },
  },
  {
    id: 'customer-availability',
    name: 'Check Customer Availability',
    category: 'Onboarding',
    method: 'POST',
    endpoint: '/Onboarding/Customer/Availability',
    requiresAuth: true,
    description: 'Checks onboarding customer availability with channel 79 and NIC.',
    body: { msgType: 335, channel: 79, nic: '<NIC entered by user>' },
  },
];
